---

- name: AEROSPIKE | Gather OS specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: AEROSPIKE | Download sources
  unarchive:
    src: "{{ aerospike_source_url }}/{{ aerospike_os }}{{ aerospike_os_major_version }}"
    dest: /tmp
    owner: root
    group: root
    remote_src: yes
    creates: "/tmp/aerospike-server-community-{{ aerospike_version }}-{{ aerospike_os }}{{ aerospike_os_major_version }}{{ aerospike_os_minor_version }}"

- name: AEROSPIKE | Installation
  shell: ./asinstall
  args:
    chdir: "/tmp/aerospike-server-community-{{ aerospike_version }}-{{ aerospike_os }}{{ aerospike_os_major_version }}{{ aerospike_os_minor_version }}"

- name: AEROSPIKE | Configuration
  template:
    src: "etc/aerospike/{{ item }}.j2"
    dest: "/etc/aerospike/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - aerospike.conf
    - astools.conf
  notify: Restart aerospike
  tags: config

- name: AEROSPIKE | Create log directory
  file:
    state: directory
    path: /var/log/aerospike
    owner: root
    group: root
    mode: 0755

- name: AEROSPIKE | Configure logs rotation
  template:
    src: "etc/logrotate.d/aerospike.j2"
    dest: "/etc/logrotate.d/aerospike"
    owner: root
    group: root
    mode: 0644
